apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-php-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mysql-minikube/

---

apiVersion: v1
kind: PersistentVolumeClaim:
metadata:
  name: mysql-php-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php-replica
      
  